### ISSUE TITLE
Installing s3fs on Python 3.10 installs old incompatible botocore

### ISSUE THREAD

**Issue by djhoese** [conda-forge/botocore-feedstock#1031]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Using `mamba`, if you install python and s3fs you will get an environment with Python 3.10.4 and botocore 1.10.58. This wouldn't be a huge issue if that version did everything you want, but that version isn't compatible with Python 3.10 and trying to import botocore produces:

```python-traceback
$ python -c "import botocore.credentials"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/credentials.py", line 30, in <module>
    import botocore.configloader
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/compat.py", line 25, in <module>
    from botocore.exceptions import MD5UnavailableError
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/exceptions.py", line 15, in <module>
    from botocore.vendored.requests.exceptions import ConnectionError
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/vendored/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/vendored/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/vendored/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/vendored/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 9, in <module>
    from ._collections import HTTPHeaderDict
  File "/home/davidh/miniconda3/envs/s3fs/lib/python3.10/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/home/davidh/miniconda3/envs/s3fs/lib/python3.10/collections/__init__.py)
```

```
$ mamba --version
mamba 0.23.0
conda 4.12.0
```

I'm not sure if this should be filed here or with mamba so I'm starting here.

### Installed packages

```shell
# packages in environment at /home/davidh/miniconda3/envs/s3fs:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiobotocore               0.10.0                     py_0    conda-forge
aiohttp                   3.8.1           py310h5764c6d_1    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
botocore                  1.10.58                    py_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
docutils                  0.18.1          py310hff52083_1    conda-forge
frozenlist                1.3.0           py310h5764c6d_1    conda-forge
fsspec                    2021.7.0           pyhd8ed1ab_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_16    conda-forge
libgomp                   11.2.0              h1d223b6_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
multidict                 6.0.2           py310h5764c6d_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.3                h166bdaf_0    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
python                    3.10.4          h2660328_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
s3fs                      2021.7.0           pyhd8ed1ab_0    conda-forge
setuptools                62.1.0          py310hff52083_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.4               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
typing-extensions         4.2.0                hd8ed1ab_1    conda-forge
typing_extensions         4.2.0              pyha770c72_1    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1          py310h5764c6d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yarl                      1.7.2           py310h5764c6d_2    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
```

### Environment info

```shell
active environment : s3fs
    active env location : /home/davidh/miniconda3/envs/s3fs
            shell level : 2
       user config file : /home/davidh/.condarc
 populated config files : /home/davidh/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.16.19=0
                          __glibc=2.34=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/davidh/miniconda3  (writable)
      conda av data dir : /home/davidh/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/davidh/miniconda3/pkgs
                          /home/davidh/.conda/pkgs
       envs directories : /home/davidh/miniconda3/envs
                          /home/davidh/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.3 Linux/5.16.19-76051619-generic pop/21.10 glibc/2.34
                UID:GID : 53807:1000
             netrc file : None
           offline mode : False
```

**Comment by bollwyvl** [comment]
Can't seem to reproduce that set of versions, when just solving against `conda-forge`, perhaps try:

```bash
mamba create -n foo --dry-run -c conda-forge -c nodefaults s3fs
```

yields:

```
  + botocore              1.24.21  pyhd8ed1ab_1        conda-forge/noarch
  + s3fs                 2022.3.0  pyhd8ed1ab_0        conda-forge/noarch
  + python                 3.10.4  h9a8a25e_0_cpython  conda-forge/linux-64
```

<details>
<pre>
  Package                 Version  Build               Channel                    Size
────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex             0.1  conda_forge         conda-forge/linux-64
  + _openmp_mutex             4.5  2_gnu               conda-forge/linux-64
  + aiobotocore             2.2.0  pyhd8ed1ab_0        conda-forge/noarch
  + aiohttp                 3.8.1  py310h5764c6d_1     conda-forge/linux-64
  + aioitertools           0.10.0  pyhd8ed1ab_0        conda-forge/noarch
  + aiosignal               1.2.0  pyhd8ed1ab_0        conda-forge/noarch
  + async-timeout           4.0.2  pyhd8ed1ab_0        conda-forge/noarch
  + attrs                  21.4.0  pyhd8ed1ab_0        conda-forge/noarch
  + botocore              1.24.21  pyhd8ed1ab_1        conda-forge/noarch
  + brotlipy                0.7.0  py310h5764c6d_1004  conda-forge/linux-64
  + bzip2                   1.0.8  h7f98852_4          conda-forge/linux-64
  + ca-certificates     2021.10.8  ha878542_0          conda-forge/linux-64
  + certifi             2021.10.8  py310hff52083_2     conda-forge/linux-64
  + cffi                   1.15.0  py310h0fdd8cc_0     conda-forge/linux-64
  + charset-normalizer     2.0.12  pyhd8ed1ab_0        conda-forge/noarch
  + cryptography           36.0.2  py310h597c629_1     conda-forge/linux-64
  + frozenlist              1.3.0  py310h5764c6d_1     conda-forge/linux-64
  + fsspec               2022.3.0  pyhd8ed1ab_0        conda-forge/noarch
  + idna                      3.3  pyhd8ed1ab_0        conda-forge/noarch
  + jmespath                1.0.0  pyhd8ed1ab_0        conda-forge/noarch
  + ld_impl_linux-64       2.36.1  hea4e1c9_2          conda-forge/linux-64
  + libffi                  3.4.2  h7f98852_5          conda-forge/linux-64
  + libgcc-ng              11.2.0  h1d223b6_16         conda-forge/linux-64
  + libgomp                11.2.0  h1d223b6_16         conda-forge/linux-64
  + libnsl                  2.0.0  h7f98852_0          conda-forge/linux-64
  + libuuid                2.32.1  h7f98852_1000       conda-forge/linux-64
  + libzlib                1.2.11  h166bdaf_1014       conda-forge/linux-64
  + multidict               6.0.2  py310h5764c6d_1     conda-forge/linux-64
  + ncurses                   6.3  h27087fc_1          conda-forge/linux-64
  + openssl                1.1.1o  h166bdaf_0          conda-forge/linux-64
  + pip                    22.0.4  pyhd8ed1ab_0        conda-forge/noarch
  + pycparser                2.21  pyhd8ed1ab_0        conda-forge/noarch
  + pyopenssl              22.0.0  pyhd8ed1ab_0        conda-forge/noarch
  + pysocks                 1.7.1  py310hff52083_5     conda-forge/linux-64
  + python                 3.10.4  h9a8a25e_0_cpython  conda-forge/linux-64
  + python-dateutil         2.8.2  pyhd8ed1ab_0        conda-forge/noarch
  + python_abi               3.10  2_cp310             conda-forge/linux-64
  + readline                  8.1  h46c0cb4_0          conda-forge/linux-64
  + s3fs                 2022.3.0  pyhd8ed1ab_0        conda-forge/noarch
  + setuptools             62.1.0  py310hff52083_0     conda-forge/linux-64
  + six                    1.16.0  pyh6c4a22f_0        conda-forge/noarch
  + sqlite                 3.38.4  h4ff8645_0          conda-forge/linux-64
  + tk                     8.6.12  h27826a3_0          conda-forge/linux-64
  + typing-extensions       4.2.0  hd8ed1ab_1          conda-forge/noarch
  + typing_extensions       4.2.0  pyha770c72_1        conda-forge/noarch
  + tzdata                  2022a  h191b570_0          conda-forge/noarch
  + urllib3                1.26.9  pyhd8ed1ab_0        conda-forge/noarch
  + wheel                  0.37.1  pyhd8ed1ab_0        conda-forge/noarch
  + wrapt                  1.14.1  py310h5764c6d_0     conda-forge/linux-64
  + xz                      5.2.5  h516909a_1          conda-forge/linux-64
  + yarl                    1.7.2  py310h5764c6d_2     conda-forge/linux-64
  + zlib                   1.2.11  h166bdaf_1014       conda-forge/linux-64
</pre>
</details>

**Comment by djhoese** [comment]
You're right that that works, but it seems only because you aren't specifying `python` in your package list.

```
mamba create -n foo --dry-run -c conda-forge -c nodefaults python s3fs
```

yields:

```
  + botocore              1.10.58  py_0                conda-forge/noarch       Cached
  + openssl                 3.0.3  h166bdaf_0          conda-forge/linux-64     Cached
  + python                 3.10.4  h2660328_0_cpython  conda-forge/linux-64     Cached
  + s3fs                 2021.7.0  pyhd8ed1ab_0        conda-forge/noarch       Cached
```

I had not specified the `-c nodefaults` in my original tests. I guess I'm not up to date on the modern best practices of using mamba/conda. This problem originally started by using mambaforge from a docker container. I guess I assumed the `*forge` distributions would have disabled defaults by default.

Either way, seems like specifying `python` in the list messes it up somehow.

**Comment by bollwyvl** [comment]
> modern best practices 

I've seen an increasing amount of stuff get weird when starting with an interactively-upgraded miniconda: things were better for a while, but not sure who's minding the shop downstream anymore... and there can be config settings all over.

anyhow, I don't have a horse in the race, as i'm not a maintainer here, but adding `python` _also_ doesn't yield the old package constellation:

```
mamba create -n foo --dry-run -c conda-forge -c nodefaults s3fs python
```

yields:

<details>
<pre>
  + _libgcc_mutex             0.1  conda_forge         conda-forge/linux-64     Cached
  + _openmp_mutex             4.5  2_gnu               conda-forge/linux-64     Cached
  + aiobotocore             2.2.0  pyhd8ed1ab_0        conda-forge/noarch         49kB
  + aiohttp                 3.8.1  py310h5764c6d_1     conda-forge/linux-64      599kB
  + aioitertools           0.10.0  pyhd8ed1ab_0        conda-forge/noarch         22kB
  + aiosignal               1.2.0  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + async-timeout           4.0.2  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + attrs                  21.4.0  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + botocore              1.24.21  pyhd8ed1ab_1        conda-forge/noarch          6MB
  + brotlipy                0.7.0  py310h5764c6d_1004  conda-forge/linux-64     Cached
  + bzip2                   1.0.8  h7f98852_4          conda-forge/linux-64     Cached
  + ca-certificates     2021.10.8  ha878542_0          conda-forge/linux-64     Cached
  + certifi             2021.10.8  py310hff52083_2     conda-forge/linux-64     Cached
  + cffi                   1.15.0  py310h0fdd8cc_0     conda-forge/linux-64     Cached
  + charset-normalizer     2.0.12  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + cryptography           36.0.2  py310h597c629_1     conda-forge/linux-64     Cached
  + frozenlist              1.3.0  py310h5764c6d_1     conda-forge/linux-64       44kB
  + fsspec               2022.3.0  pyhd8ed1ab_0        conda-forge/noarch         95kB
  + idna                      3.3  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + jmespath                1.0.0  pyhd8ed1ab_0        conda-forge/noarch         21kB
  + ld_impl_linux-64       2.36.1  hea4e1c9_2          conda-forge/linux-64     Cached
  + libffi                  3.4.2  h7f98852_5          conda-forge/linux-64     Cached
  + libgcc-ng              11.2.0  h1d223b6_16         conda-forge/linux-64     Cached
  + libgomp                11.2.0  h1d223b6_16         conda-forge/linux-64     Cached
  + libnsl                  2.0.0  h7f98852_0          conda-forge/linux-64     Cached
  + libuuid                2.32.1  h7f98852_1000       conda-forge/linux-64     Cached
  + libzlib                1.2.11  h166bdaf_1014       conda-forge/linux-64     Cached
  + multidict               6.0.2  py310h5764c6d_1     conda-forge/linux-64       53kB
  + ncurses                   6.3  h27087fc_1          conda-forge/linux-64     Cached
  + openssl                1.1.1o  h166bdaf_0          conda-forge/linux-64        2MB
  + pip                    22.0.4  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + pycparser                2.21  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + pyopenssl              22.0.0  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + pysocks                 1.7.1  py310hff52083_5     conda-forge/linux-64     Cached
  + python                 3.10.4  h9a8a25e_0_cpython  conda-forge/linux-64     Cached
  + python-dateutil         2.8.2  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + python_abi               3.10  2_cp310             conda-forge/linux-64     Cached
  + readline                  8.1  h46c0cb4_0          conda-forge/linux-64     Cached
  + s3fs                 2022.3.0  pyhd8ed1ab_0        conda-forge/noarch         26kB
  + setuptools             62.1.0  py310hff52083_0     conda-forge/linux-64     Cached
  + six                    1.16.0  pyh6c4a22f_0        conda-forge/noarch       Cached
  + sqlite                 3.38.4  h4ff8645_0          conda-forge/linux-64        2MB
  + tk                     8.6.12  h27826a3_0          conda-forge/linux-64     Cached
  + typing-extensions       4.2.0  hd8ed1ab_1          conda-forge/noarch       Cached
  + typing_extensions       4.2.0  pyha770c72_1        conda-forge/noarch       Cached
  + tzdata                  2022a  h191b570_0          conda-forge/noarch       Cached
  + urllib3                1.26.9  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + wheel                  0.37.1  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + wrapt                  1.14.1  py310h5764c6d_0     conda-forge/linux-64       52kB
  + xz                      5.2.5  h516909a_1          conda-forge/linux-64     Cached
  + yarl                    1.7.2  py310h5764c6d_2     conda-forge/linux-64      136kB
  + zlib                   1.2.11  h166bdaf_1014       conda-forge/linux-64     Cached
</pre>
</details>

i think it  will be hard to figure out who, precisely, is "at fault," and this might be a situation where some sane bottom pins are going to be necessary.

**Comment by wroberts4** [comment]
I get the same error when doing the following both inside docker and on multiple local machines:
```
$ docker run --rm condaforge/mambaforge:4.12.0-0 mamba --version
mamba 0.22.1
conda 4.12.0
$ docker run --rm condaforge/mambaforge:4.12.0-0 bash -c 'mamba create -y -n foo -c conda-forge -c nodefaults python s3fs; mamba run -n foo python -c "import botocore.credentials"'
```
However, the strange thing is that the following works:
```
$ docker run --rm condaforge/mambaforge:4.12.0-0 bash -c 'mamba create -y -n foo -c conda-forge -c nodefaults python; mamba install -y -n foo -c conda-forge -c nodefaults s3fs; mamba run -n foo python -c "import botocore.credentials"'
```
Another option that works:
```
$ docker run --rm condaforge/mambaforge:4.12.0-0 bash -c 'mamba create -y -n foo -c conda-forge -c nodefaults python=3.8 s3fs; mamba run -n foo python -c "import botocore.credentials"'
```
However if I use python 3.9+, it fails

**Comment by djhoese** [comment]
@bollwyvl Put `python` first. Then it uses the old botocore.

**Comment by bollwyvl** [comment]
crazy. welp, i'm outta ideas, then: @wolfv any thoughts?

**Comment by wolfv** [comment]
I think this is maybe a similar problem to https://github.com/mamba-org/mamba/issues/1581 where mamba picks an old jupyterlab to get the newest openssl. I think we need to tackle this ...

**Comment by djhoese** [comment]
Yes I noticed that @wolfv. When debugging with @wroberts4 we noticed that the main difference between the environments was the build of python. Not a version or even build number change just the SSL that was used when built.

**Comment by tkelman** [comment]
I don't think the bug has anything to do with the contents of the recipe here?

**Comment by djhoese** [comment]
@tkelman Hard to say unless someone has a better idea of why it is happening. Could it be a bug in mamba? Possibly/Probably. Could it be some metadata being produced by this recipe that is confusing things? Possibly. If you'd like this to be closed then I/we need to make a bug report on the mamba project.

**Comment by tkelman** [comment]
I see nothing special about 1.10.58 vs later versions? ref https://github.com/conda-forge/botocore-feedstock/commit/c7c72626f34bb42443f5e3035e5f329d65b253de

I'd be inclined to migrate the issue over to mamba. I thought github had new features for moving issues including the entire comment thread but maybe that's only doable within an org?

**Comment by tkelman** [comment]
I guess we could also go through a whole bunch of past versions and mark the ones that are broken on latest python with tighter requirements, but that sounds like a lot of work and I'm not sure if it's even possible with the builds being noarch.

**Comment by djhoese** [comment]
Created https://github.com/mamba-org/mamba/issues/1672

**Comment by djhoese** [comment]
Turns out it was a duplicate so the issue to watch is: https://github.com/mamba-org/mamba/issues/1581

**Comment by tkelman** [comment]
Thanks for the update. I think I'll close here.
