### ISSUE TITLE
Issue with the urllib3 dependancy

### ISSUE THREAD

**Issue by HeavyTony2** [conda-forge/botocore-feedstock#1465]
I'm currently unable to get the updated recipe for the resdk package, except if I decide to sacrifice python 3.10 and 3.11. https://github.com/conda-forge/resdk-feedstock/pull/9/

For example, if I remove the noarch and list the deps
```
    - urllib3  >=2  # [py>=310]
    - urllib3 >=1.25.4,<1.27  # [py<310]
```
I get this result for a.10 and 3.11 :
```
- urllib3 >=2
 - openpyxl
 - python >=3.11,<3.12.0a0
 - importlib-metadata
 - tzlocal >=1.5.1
 - pandas >=1.0.0
 - mypy-boto3-s3
 - tqdm
 - slumber >=0.7.1
 - boto3-stubs >=1.24,<2.dev0
 - wrapt
 - requests >=2.6.0
 - xlrd
 - boto3 >=1.24,<2.dev0
 - pytz >=2018.4
 - aiohttp >=3.8.5,<3.9.dev0

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package boto3-1.24.0-pyhd8ed1ab_0 requires botocore >=1.27.0,<1.28.0, but none of the providers can be installed
```
If I had botocore to the deps

```
    - urllib3  >=2  # [py>=310]
    - urllib3 >=1.25.4,<1.27  # [py<310]
    - botocore
```
Here's the result:
The reported errors are:
```
- Encountered problems while solving:
-   - package botocore-1.27.0-pyhd8ed1ab_0 requires urllib3 >=1.25.4,<1.27, but none of the providers can be installed

```
So basically, the botocore package is set to get the wrong urllib3 versions for python 3.10 higher.

**Comment by tkelman** [comment]
Upstream never imposes a `>=2`, but I did make a note when they loosened the upper bound for python 3.10 and higher (https://github.com/boto/botocore/commit/785d22457779cdb4054b77f4bd8fbca3feaf45a2) that I don't think supporting that is compatible with noarch here https://github.com/conda-forge/botocore-feedstock/pull/1387/commits/ddbfb34eb3a5ed44e558ef30af6a4e5f2ea60625

**Comment by HeavyTony2** [comment]
> Upstream never imposes a `>=2`

I realize this is specifically required by Resdk while Botocore is more flexible. https://github.com/genialis/resolwe-bio-py/blob/a3fccbcdae442d6554bf7f435a05c53e85c898de/pyproject.toml#L45 https://github.com/boto/botocore/blob/6df686813e948b59bcb9207e3379a790a4e83575/setup.py#L29

In theory, Botocore's recipe should not be currently set in noarch mode because of that difference between >=3.10 and <3.10. Would it be okay to update the recipe to turn it in non-no-arch and then reupdate it to turn it back to no-arch?

**Comment by tkelman** [comment]
Not quite sure what you're asking for then, do you mostly want one specific build to exist? Or for things to be maintained with the loosened dependencies indefinitely? If it's more the former, we could try making a branch that turns off noarch and occasionally manually update new builds from it going forward (until conda-forge drops python 3.9 and earlier).

**Comment by HeavyTony2** [comment]
I was indeed asking for the first option.

**Comment by tkelman** [comment]
Okay sure, I made a branch https://github.com/conda-forge/botocore-feedstock/compare/main...arch-specific that now has a v1.34.33-2 build you should be able to try out.
